export const categoriesFirstPage = [
  {
    id: 312,
    name: 'Test Product',
    slug: 'test-product',
    sortOrder: 999,
    status: 1,
    distributor: null,
    distributorCode: 'BFJWcnv6',
    percent: 1.0,
    imageFile: null,
    displayShowcaseContent: 0,
    showcaseContent: null,
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 0,
    showcaseFooterContent: null,
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: null,
    metaDescription: null,
    metaKeywords: null,
    canonicalUrl: null,
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2024-12-14T22:33:40+03:00',
  },
  {
    id: 319,
    name: 'Yağı',
    slug: 'yagi',
    sortOrder: 999,
    status: 1,
    distributor: null,
    distributorCode: 'STUVWw14',
    percent: 1.0,
    imageFile: null,
    displayShowcaseContent: 0,
    showcaseContent: '123123',
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 0,
    showcaseFooterContent: null,
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: null,
    metaDescription: null,
    metaKeywords: 'Taho1',
    canonicalUrl: null,
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2024-12-15T12:48:46+03:00',
  },
  {
    id: 320,
    name: 'Pogaca',
    slug: 'pogaca',
    sortOrder: 999,
    status: 0,
    distributor: null,
    distributorCode: 'MNTYZd15',
    percent: 1.0,
    imageFile: null,
    displayShowcaseContent: 0,
    showcaseContent: '123123',
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 0,
    showcaseFooterContent: null,
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: null,
    metaDescription: null,
    metaKeywords: 'Pogaca',
    canonicalUrl: null,
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2024-12-15T12:49:21+03:00',
  },
  {
    id: 322,
    name: 'Çay ',
    slug: 'cay',
    sortOrder: 999,
    status: 1,
    distributor: null,
    distributorCode: 'RScgjw89',
    percent: 1.0,
    imageFile: null,
    displayShowcaseContent: 0,
    showcaseContent: 'Çay ',
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 0,
    showcaseFooterContent: null,
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: null,
    metaDescription: null,
    metaKeywords: 'Çay c',
    canonicalUrl: null,
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2024-12-15T12:56:36+03:00',
  },
  {
    id: 327,
    name: 'Test Product',
    slug: 'test-product-3',
    sortOrder: 999,
    status: 0,
    distributor: null,
    distributorCode: 'GNPZbcs9',
    percent: 1.0,
    imageFile: null,
    displayShowcaseContent: 0,
    showcaseContent: 'Aaaaa',
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 0,
    showcaseFooterContent: null,
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: null,
    metaDescription: null,
    metaKeywords: 'Aaaa',
    canonicalUrl: null,
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2024-12-15T14:00:26+03:00',
  },
  {
    id: 377,
    name: 'TEST UPDATE',
    slug: 'test-update',
    sortOrder: 1,
    status: 1,
    distributor: null,
    distributorCode: 'Fbdin349',
    percent: 1.0,
    imageFile: null,
    displayShowcaseContent: 1,
    showcaseContent: null,
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 1,
    showcaseFooterContent: null,
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: 'T',
    metaDescription: 'T',
    metaKeywords: 'T',
    canonicalUrl: 'T',
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 1,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2024-12-27T03:10:16+03:00',
  },
  {
    id: 383,
    name: 'Test Safa',
    slug: 'test',
    sortOrder: 999,
    status: 1,
    distributor: null,
    distributorCode: 'EGMTfhst',
    percent: 1.0,
    imageFile: null,
    displayShowcaseContent: 1,
    showcaseContent: null,
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 1,
    showcaseFooterContent: null,
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: '1',
    metaDescription: '1',
    metaKeywords: '1',
    canonicalUrl: '1',
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 1,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2024-12-27T03:13:34+03:00',
  },
  {
    id: 384,
    name: 'Test safa',
    slug: 'test-1',
    sortOrder: 999,
    status: 0,
    distributor: null,
    distributorCode: 'CQSZfhx5',
    percent: 1.0,
    imageFile: null,
    displayShowcaseContent: 0,
    showcaseContent: null,
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 0,
    showcaseFooterContent: null,
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: '',
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2024-12-27T03:18:23+03:00',
  },
  {
    id: 385,
    name: 'Test safa',
    slug: 'test-safa-slug',
    sortOrder: 999,
    status: 0,
    distributor: null,
    distributorCode: 'GUZbxz36',
    percent: 1.0,
    imageFile: null,
    displayShowcaseContent: 0,
    showcaseContent: null,
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 0,
    showcaseFooterContent: null,
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: '',
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2024-12-27T03:20:47+03:00',
  },
  {
    id: 386,
    name: 'Test Safa',
    slug: 'test-safa',
    sortOrder: 99,
    status: 0,
    distributor: null,
    distributorCode: 'DFGLNSak',
    percent: 1.0,
    imageFile: null,
    displayShowcaseContent: 1,
    showcaseContent: 'açıklama',
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 0,
    showcaseFooterContent: null,
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: '',
    metaDescription: 'açıklamaa düzeltildi emir',
    metaKeywords: 'açıklama',
    canonicalUrl: '',
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 1,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2024-12-27T03:31:16+03:00',
  },
  {
    id: 448,
    name: 'One',
    slug: 'one',
    sortOrder: 999,
    status: 1,
    distributor: null,
    distributorCode: 'TZjnrv89',
    percent: 1.0,
    imageFile: null,
    displayShowcaseContent: 0,
    showcaseContent: null,
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 0,
    showcaseFooterContent: null,
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: null,
    metaDescription: null,
    metaKeywords: null,
    canonicalUrl: null,
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2025-01-15T05:14:07+03:00',
  },
  {
    id: 450,
    name: 'Two',
    slug: 'two',
    sortOrder: 999,
    status: 1,
    distributor: null,
    distributorCode: 'NWdhnrs7',
    percent: 1.0,
    imageFile: null,
    displayShowcaseContent: 0,
    showcaseContent: null,
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 0,
    showcaseFooterContent: null,
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: null,
    metaDescription: null,
    metaKeywords: null,
    canonicalUrl: null,
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2025-01-15T05:14:12+03:00',
  },
  {
    id: 455,
    name: 'Four e',
    slug: 'four',
    sortOrder: 999,
    status: 1,
    distributor: null,
    distributorCode: 'DFQWgirt',
    percent: 1.0,
    imageFile: null,
    displayShowcaseContent: 0,
    showcaseContent: null,
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 0,
    showcaseFooterContent: null,
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: null,
    metaDescription: null,
    metaKeywords: null,
    canonicalUrl: null,
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2025-01-15T05:15:27+03:00',
  },
  {
    id: 462,
    name: 'Kırtasiye',
    slug: 'kirtasiye',
    sortOrder: 999,
    status: 1,
    distributor: null,
    distributorCode: 'LNVtw358',
    percent: 1.0,
    imageFile: null,
    displayShowcaseContent: 0,
    showcaseContent: null,
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 0,
    showcaseFooterContent: null,
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: null,
    metaDescription: null,
    metaKeywords: null,
    canonicalUrl: null,
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2025-01-15T05:21:44+03:00',
  },
  {
    id: 465,
    name: 'Yeni kategori deneme',
    slug: 'new-category',
    sortOrder: 0,
    status: 1,
    distributor: 'Şeffaf',
    distributorCode: 'CTdhin19',
    percent: 0.0,
    imageFile: null,
    displayShowcaseContent: 1,
    showcaseContent: 'Test showcase',
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 1,
    showcaseFooterContent: 'Test showcase footer',
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: 'Yeni Kategori',
    metaDescription: 'Meta category',
    metaKeywords: 'Newcategory',
    canonicalUrl: 'https://google.com',
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2025-01-15T14:37:57+03:00',
  },
  {
    id: 466,
    name: 'Metro new category',
    slug: 'metro',
    sortOrder: 0,
    status: 1,
    distributor: 'Yeni distributor',
    distributorCode: 'CFMPr234',
    percent: 10.0,
    imageFile: null,
    displayShowcaseContent: 1,
    showcaseContent: 'Üst içerik metni hazır ',
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 1,
    showcaseFooterContent: 'Footer üst içerik metni hazırdır ',
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: 'Merto new category',
    metaDescription: 'Selam',
    metaKeywords: 'Test merto kategori',
    canonicalUrl: 'New categoryyyyyy',
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2025-01-15T14:39:28+03:00',
  },
  {
    id: 474,
    name: 'Add',
    slug: 'add',
    sortOrder: 0,
    status: 1,
    distributor: 'Add',
    distributorCode: 'HJSVrv67',
    percent: 0.0,
    imageFile: null,
    displayShowcaseContent: 1,
    showcaseContent: 'Add',
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 1,
    showcaseFooterContent: 'Add',
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: 'Asd',
    metaDescription: 'Asd',
    metaKeywords: 'Asd',
    canonicalUrl: 'Asd',
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2025-01-15T14:44:42+03:00',
  },
  {
    id: 475,
    name: '123',
    slug: '123',
    sortOrder: 123,
    status: 1,
    distributor: '23',
    distributorCode: 'CJUVmnv5',
    percent: 123.0,
    imageFile: null,
    displayShowcaseContent: 1,
    showcaseContent: '123',
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 1,
    showcaseFooterContent: '1231',
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: '123',
    metaDescription: '123',
    metaKeywords: '123',
    canonicalUrl: '123',
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2025-01-15T14:47:11+03:00',
  },
  {
    id: 476,
    name: '123',
    slug: 'asdasd',
    sortOrder: 0,
    status: 1,
    distributor: 'Asd',
    distributorCode: 'LPVYdv56',
    percent: 0.0,
    imageFile: null,
    displayShowcaseContent: 1,
    showcaseContent: 'Asd',
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 1,
    showcaseFooterContent: 'Asd',
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: 'Asd',
    metaDescription: 'Asd',
    metaKeywords: 'Asd',
    canonicalUrl: 'Asd',
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2025-01-15T14:48:16+03:00',
  },
  {
    id: 477,
    name: 'Test Product Update 5234',
    slug: 'slug-1',
    sortOrder: 5,
    status: 1,
    distributor: '',
    distributorCode: 'DFJcdmy4',
    percent: 1.0,
    imageFile: null,
    displayShowcaseContent: 1,
    showcaseContent: 'Showcase content',
    showcaseContentDisplayType: 1,
    displayShowcaseFooterContent: 1,
    showcaseFooterContent: '',
    showcaseFooterContentDisplayType: 1,
    hasChildren: 0,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '424242',
    canonicalUrl: '',
    parent: null,
    children: [],
    imageUrl: null,
    isCombine: 0,
    isSearchable: 1,
    seoSetting: null,
    createdAt: '2025-01-15T14:55:04+03:00',
  },
];
