export const productsFirstPage = [
  {
    id: 542,
    name: 'fotoğraflı ürün',
    fullName: 'fotoğraflı ürün',
    slug: 'fotografli-urunr',
    sku: 'FT-24',
    barcode: '2434FT',
    stockAmount: 10.0,
    price1: 1000.0,
    currency: {
      id: 3,
      label: 'TL',
      abbr: 'TL',
    },
    discount: 10.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 10,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: 'Türkiye',
    hasGift: 0,
    gift: '',
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: {
      id: 85,
      details: 'detaylar fotoğraf',
      extraDetails: 'detay fotoğraf',
    },
    categories: [],
    prices: [],
    images: [
      {
        id: 99,
        filename: 'e5ca1736-9d4c-461f-b7f0-54e8ad473341',
        extension: 'jpg',
        thumbUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/542/e5ca1736-9d4c-461f-b7f0-54e8ad473341_min.jpg?revision=1737037481',
        originalUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/542/e5ca1736-9d4c-461f-b7f0-54e8ad473341.jpg?revision=1737037481',
      },
      {
        id: 145,
        filename: 'img-0004',
        extension: 'jpg',
        thumbUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/542/img-0004_min.jpg?revision=1737037481',
        originalUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/542/img-0004.jpg?revision=1737037481',
      },
      {
        id: 158,
        filename: 'img-0003',
        extension: 'jpg',
        thumbUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/542/img-0003_min.jpg?revision=1737037479',
        originalUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/542/img-0003.jpg?revision=1737037479',
      },
    ],
    optionGroups: [],
    updatedAt: '2025-01-16T17:24:39+03:00',
    createdAt: '2025-01-15T12:17:27+03:00',
  },
  {
    id: 558,
    name: 'deneme',
    fullName: 'deneme',
    slug: 'deneme-1',
    sku: 'deneme2',
    barcode: null,
    stockAmount: 10.0,
    price1: 10.0,
    currency: {
      id: 5,
      label: 'JPY',
      abbr: 'JPY',
    },
    discount: 0.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 20,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: null,
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [],
    prices: [],
    images: [
      {
        id: 134,
        filename: 'img-0004',
        extension: 'jpg',
        thumbUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/558/img-0004_min.jpg?revision=1737037218',
        originalUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/558/img-0004.jpg?revision=1737037218',
      },
      {
        id: 150,
        filename: 'img-0005',
        extension: 'jpg',
        thumbUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/558/img-0005_min.jpg?revision=1737037217',
        originalUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/558/img-0005.jpg?revision=1737037217',
      },
    ],
    optionGroups: [],
    updatedAt: '2025-01-16T17:20:17+03:00',
    createdAt: '2025-01-15T19:56:35+03:00',
  },
  {
    id: 559,
    name: 'deneme',
    fullName: 'deneme',
    slug: 'deneme-2',
    sku: 'deneme3',
    barcode: null,
    stockAmount: 10.0,
    price1: 10.0,
    currency: {
      id: 10,
      label: 'AVUSTRALYA DOLARI',
      abbr: 'AUD',
    },
    discount: 0.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 20,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: null,
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [],
    prices: [],
    images: [],
    optionGroups: [],
    updatedAt: '2025-01-15T19:58:09+03:00',
    createdAt: '2025-01-15T19:58:09+03:00',
  },
  {
    id: 561,
    name: 'deneme',
    fullName: 'deneme',
    slug: 'deneme-3',
    sku: 'deneme4',
    barcode: null,
    stockAmount: 10.0,
    price1: 10.0,
    currency: {
      id: 3,
      label: 'TL',
      abbr: 'TL',
    },
    discount: 0.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 20,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: null,
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [],
    prices: [],
    images: [],
    optionGroups: [],
    updatedAt: '2025-01-15T19:58:21+03:00',
    createdAt: '2025-01-15T19:58:21+03:00',
  },
  {
    id: 562,
    name: 'deneme',
    fullName: 'deneme',
    slug: 'deneme-4',
    sku: 'deneme5',
    barcode: null,
    stockAmount: 10.0,
    price1: 10.0,
    currency: {
      id: 5,
      label: 'JPY',
      abbr: 'JPY',
    },
    discount: 0.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 20,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: null,
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [],
    prices: [],
    images: [],
    optionGroups: [],
    updatedAt: '2025-01-15T19:58:42+03:00',
    createdAt: '2025-01-15T19:58:42+03:00',
  },
  {
    id: 563,
    name: 'deneme',
    fullName: 'deneme',
    slug: 'deneme-5',
    sku: 'deneme6',
    barcode: null,
    stockAmount: 10.0,
    price1: 10.0,
    currency: {
      id: 6,
      label: 'YUAN',
      abbr: 'CNY',
    },
    discount: 0.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 20,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: null,
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [],
    prices: [],
    images: [],
    optionGroups: [],
    updatedAt: '2025-01-15T19:58:52+03:00',
    createdAt: '2025-01-15T19:58:52+03:00',
  },
  {
    id: 564,
    name: 'deneme',
    fullName: 'deneme',
    slug: 'deneme-6',
    sku: 'deneme7',
    barcode: null,
    stockAmount: 10.0,
    price1: 10.0,
    currency: {
      id: 7,
      label: 'GOLD',
      abbr: 'GR',
    },
    discount: 0.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 20,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: null,
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [],
    prices: [],
    images: [],
    optionGroups: [],
    updatedAt: '2025-01-15T19:59:03+03:00',
    createdAt: '2025-01-15T19:59:03+03:00',
  },
  {
    id: 565,
    name: 'deneme',
    fullName: 'deneme',
    slug: 'deneme-7',
    sku: 'deneme8',
    barcode: null,
    stockAmount: 10.0,
    price1: 10.0,
    currency: {
      id: 8,
      label: 'CHF',
      abbr: 'CHF',
    },
    discount: 0.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 20,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: null,
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [],
    prices: [],
    images: [],
    optionGroups: [],
    updatedAt: '2025-01-15T19:59:27+03:00',
    createdAt: '2025-01-15T19:59:27+03:00',
  },
  {
    id: 566,
    name: 'deneme',
    fullName: 'deneme',
    slug: 'deneme-8',
    sku: 'deneme9',
    barcode: null,
    stockAmount: 10.0,
    price1: 10.0,
    currency: {
      id: 9,
      label: 'YENI ZELLANDA DOLARI',
      abbr: 'NZD',
    },
    discount: 0.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 20,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: null,
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [],
    prices: [],
    images: [],
    optionGroups: [],
    updatedAt: '2025-01-15T19:59:36+03:00',
    createdAt: '2025-01-15T19:59:36+03:00',
  },
  {
    id: 567,
    name: 'deneme',
    fullName: 'deneme',
    slug: 'deneme-9',
    sku: 'deneme10',
    barcode: null,
    stockAmount: 10.0,
    price1: 10.0,
    currency: {
      id: 10,
      label: 'AVUSTRALYA DOLARI',
      abbr: 'AUD',
    },
    discount: 0.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 20,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: null,
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [],
    prices: [],
    images: [],
    optionGroups: [],
    updatedAt: '2025-01-15T20:00:02+03:00',
    createdAt: '2025-01-15T20:00:02+03:00',
  },
  {
    id: 568,
    name: 'deneme',
    fullName: 'deneme',
    slug: 'deneme-10',
    sku: 'deneme11',
    barcode: null,
    stockAmount: 11.0,
    price1: 10.0,
    currency: {
      id: 10,
      label: 'AVUSTRALYA DOLARI',
      abbr: 'AUD',
    },
    discount: 0.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 20,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: null,
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [],
    prices: [],
    images: [],
    optionGroups: [],
    updatedAt: '2025-01-15T20:10:43+03:00',
    createdAt: '2025-01-15T20:10:43+03:00',
  },
  {
    id: 569,
    name: 'Selam 123',
    fullName: 'Selam 123',
    slug: 'selam-123',
    sku: '12',
    barcode: '1233',
    stockAmount: 12.0,
    price1: 239.0,
    currency: {
      id: 1,
      label: 'USD',
      abbr: 'USD',
    },
    discount: 10.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 18,
    warranty: 12,
    volumetricWeight: 1.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: null,
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '',
    metaDescription: 'Sdfsdfds test Loren ipsum',
    metaKeywords: 'Meta 123',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: {
      id: 94,
      details: 'Product detail',
      extraDetails: 'Dfdffd',
    },
    categories: [],
    prices: [],
    images: [],
    optionGroups: [],
    updatedAt: '2025-01-15T21:45:00+03:00',
    createdAt: '2025-01-15T21:45:00+03:00',
  },
  {
    id: 570,
    name: 'Ekleme deneme',
    fullName: 'Ekleme deneme',
    slug: 'ekleme-deneme',
    sku: 'Ekle',
    barcode: null,
    stockAmount: 100.0,
    price1: 100.0,
    currency: {
      id: 4,
      label: 'POUND',
      abbr: 'GBP',
    },
    discount: 0.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 20,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: null,
    hasGift: 0,
    gift: null,
    status: 0,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [
      {
        id: 465,
        name: 'Yeni kategori deneme',
        sortOrder: 0,
        showcaseSortOrder: null,
        pageTitle: 'Yeni Kategori',
        metaDescription: 'Meta category',
        metaKeywords: 'Newcategory',
        canonicalUrl: 'https://google.com',
        tree: 'Yeni kategori deneme',
        imageUrl: null,
      },
      {
        id: 377,
        name: 'TEST UPDATE',
        sortOrder: 1,
        showcaseSortOrder: null,
        pageTitle: 'T',
        metaDescription: 'T',
        metaKeywords: 'T',
        canonicalUrl: 'T',
        tree: 'TEST UPDATE',
        imageUrl: null,
      },
      {
        id: 478,
        name: 'Test Product Update 523232',
        sortOrder: 5,
        showcaseSortOrder: null,
        pageTitle: null,
        metaDescription: null,
        metaKeywords: '424242',
        canonicalUrl: null,
        tree: 'Test Product Update 523232',
        imageUrl: null,
      },
    ],
    prices: [],
    images: [
      {
        id: 109,
        filename: 'ornek-urun-gorseli-3',
        extension: 'jpg',
        thumbUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/570/ornek-urun-gorseli-3_min.jpg?revision=1737035763',
        originalUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/570/ornek-urun-gorseli-3.jpg?revision=1737035763',
      },
      {
        id: 133,
        filename: 'img-0001',
        extension: 'jpg',
        thumbUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/570/img-0001_min.jpg?revision=1737035761',
        originalUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/570/img-0001.jpg?revision=1737035761',
      },
    ],
    optionGroups: [],
    updatedAt: '2025-01-16T16:56:01+03:00',
    createdAt: '2025-01-16T03:13:15+03:00',
  },
  {
    id: 571,
    name: 'Gorsel deneme',
    fullName: 'Gorsel deneme',
    slug: 'gorsel-deneme',
    sku: 'Gorseldeneme',
    barcode: null,
    stockAmount: 100.0,
    price1: 100.0,
    currency: {
      id: 4,
      label: 'POUND',
      abbr: 'GBP',
    },
    discount: 0.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 20,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: null,
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [],
    prices: [],
    images: [],
    optionGroups: [],
    updatedAt: '2025-01-16T16:32:05+03:00',
    createdAt: '2025-01-16T16:32:05+03:00',
  },
  {
    id: 575,
    name: 'Deneme',
    fullName: 'Deneme',
    slug: 'deneme',
    sku: 'Aaaa',
    barcode: null,
    stockAmount: 100.0,
    price1: 100.0,
    currency: {
      id: 1,
      label: 'USD',
      abbr: 'USD',
    },
    discount: 0.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 20,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: null,
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [],
    prices: [],
    images: [],
    optionGroups: [],
    updatedAt: '2025-01-16T16:33:21+03:00',
    createdAt: '2025-01-16T16:33:21+03:00',
  },
  {
    id: 583,
    name: 'Deneme',
    fullName: 'Deneme',
    slug: 'deneme-12',
    sku: '11',
    barcode: null,
    stockAmount: 11.0,
    price1: 11.0,
    currency: {
      id: 4,
      label: 'POUND',
      abbr: 'GBP',
    },
    discount: 0.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 20,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: null,
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '',
    metaDescription: '',
    metaKeywords: '',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [],
    prices: [],
    images: [
      {
        id: 136,
        filename: 'img-0004',
        extension: 'jpg',
        thumbUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/583/img-0004_min.jpg?revision=1737037577',
        originalUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/583/img-0004.jpg?revision=1737037577',
      },
      {
        id: 159,
        filename: 'img-0005',
        extension: 'jpg',
        thumbUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/583/img-0005_min.jpg?revision=1737037576',
        originalUrl:
          '//ideacdn.net/idea/kh/32/myassets/products/583/img-0005.jpg?revision=1737037576',
      },
    ],
    optionGroups: [],
    updatedAt: '2025-01-16T17:26:16+03:00',
    createdAt: '2025-01-16T16:58:56+03:00',
  },
  {
    id: 589,
    name: 'Fsdfsd',
    fullName: 'Fsdfsd',
    slug: 'fsdfsd',
    sku: '214214',
    barcode: 'Ggdfgdfg',
    stockAmount: 124124.0,
    price1: 2412412.0,
    currency: {
      id: 1,
      label: 'USD',
      abbr: 'USD',
    },
    discount: 5.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 18,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: 'SuperTedarik',
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: 'Fsdfsd',
    metaDescription: 'Kaliteli ürünler.',
    metaKeywords: 'fsdfsd',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [
      {
        id: 312,
        name: 'Test Product',
        sortOrder: 999,
        showcaseSortOrder: null,
        pageTitle: null,
        metaDescription: null,
        metaKeywords: null,
        canonicalUrl: null,
        tree: 'Test Product',
        imageUrl: null,
      },
    ],
    prices: [],
    images: [],
    optionGroups: [],
    updatedAt: '2025-01-16T22:20:06+03:00',
    createdAt: '2025-01-16T22:20:06+03:00',
  },
  {
    id: 590,
    name: 'Deneme2',
    fullName: 'Deneme2',
    slug: 'deneme2',
    sku: '43534',
    barcode: 'Ddhdf',
    stockAmount: 213131.0,
    price1: 121213.0,
    currency: {
      id: 1,
      label: 'USD',
      abbr: 'USD',
    },
    discount: 5.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 18,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: 'SuperTedarik',
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: 'Sgsdgsd',
    metaDescription: 'Dgdfgdfdg',
    metaKeywords: 'Dgsdgsdg',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [
      {
        id: 320,
        name: 'Pogaca',
        sortOrder: 999,
        showcaseSortOrder: null,
        pageTitle: null,
        metaDescription: null,
        metaKeywords: 'Pogaca',
        canonicalUrl: null,
        tree: 'Pogaca',
        imageUrl: null,
      },
    ],
    prices: [],
    images: [],
    optionGroups: [],
    updatedAt: '2025-01-16T22:37:30+03:00',
    createdAt: '2025-01-16T22:37:30+03:00',
  },
  {
    id: 591,
    name: 'Jggk',
    fullName: 'Jggk',
    slug: 'jggk',
    sku: '67866767',
    barcode: 'Hhgjghjghjghj',
    stockAmount: 676767768.0,
    price1: 76676767.0,
    currency: {
      id: 1,
      label: 'USD',
      abbr: 'USD',
    },
    discount: 5.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 18,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: 'SuperTedarik',
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: 'Gghghghhghghj',
    metaDescription: 'Gghghghgh',
    metaKeywords: 'Gghghghj',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [
      {
        id: 320,
        name: 'Pogaca',
        sortOrder: 999,
        showcaseSortOrder: null,
        pageTitle: null,
        metaDescription: null,
        metaKeywords: 'Pogaca',
        canonicalUrl: null,
        tree: 'Pogaca',
        imageUrl: null,
      },
    ],
    prices: [],
    images: [],
    optionGroups: [],
    updatedAt: '2025-01-16T22:42:25+03:00',
    createdAt: '2025-01-16T22:42:25+03:00',
  },
  {
    id: 592,
    name: 'Hghghgh',
    fullName: 'Hghghgh',
    slug: 'hghghgh',
    sku: '676676767',
    barcode: '67676767',
    stockAmount: 678676767678.0,
    price1: 787767667.0,
    currency: {
      id: 1,
      label: 'USD',
      abbr: 'USD',
    },
    discount: 5.0,
    discountType: 1,
    moneyOrderDiscount: 0.0,
    buyingPrice: 0.0,
    marketPriceDetail: null,
    taxIncluded: 0,
    tax: 18,
    warranty: 24,
    volumetricWeight: 0.0,
    stockTypeLabel: 'Piece',
    customShippingDisabled: 1,
    customShippingCost: 0.0,
    distributor: null,
    hasGift: 0,
    gift: null,
    status: 1,
    hasOption: 0,
    installmentThreshold: '0',
    homeSortOrder: null,
    popularSortOrder: null,
    brandSortOrder: null,
    featuredSortOrder: null,
    campaignedSortOrder: null,
    newSortOrder: null,
    discountedSortOrder: null,
    categoryShowcaseStatus: 0,
    midblockSortOrder: null,
    pageTitle: '556656575656',
    metaDescription: '5655656565665',
    metaKeywords: '5675656565656',
    canonicalUrl: null,
    parent: null,
    brand: null,
    detail: null,
    categories: [
      {
        id: 312,
        name: 'Test Product',
        sortOrder: 999,
        showcaseSortOrder: null,
        pageTitle: null,
        metaDescription: null,
        metaKeywords: null,
        canonicalUrl: null,
        tree: 'Test Product',
        imageUrl: null,
      },
    ],
    prices: [],
    images: [],
    optionGroups: [],
    updatedAt: '2025-01-17T00:21:44+03:00',
    createdAt: '2025-01-17T00:21:44+03:00',
  },
];
